namespace nom.tam.fits.compression
{
    using System;

    /// <summary>How a floating-point image was quantized onto integers before being
    /// compressed, as declared by the <c>ZQUANTIZ</c> keyword.</summary>
    public enum QuantizationMethod
    {
        /// <summary>The tile data are not quantized at all: the compressed bytes hold
        /// the original values, so the round trip is lossless.</summary>
        None = 0,

        /// <summary>Quantized by simple truncation, with no dithering.</summary>
        NoDither = 1,

        /// <summary>Quantized after adding a pseudo-random offset, which spreads the
        /// quantization error out instead of letting it band. The same random sequence
        /// must be subtracted on the way back, which is what <c>ZDITHER0</c> anchors.</summary>
        SubtractiveDither1 = 2,

        /// <summary>As <see cref="SubtractiveDither1"/>, except that pixels which were
        /// exactly zero are recorded as such and come back exactly zero. Astronomical
        /// images use zero as "no data" often enough that dithering it would be
        /// destructive.</summary>
        SubtractiveDither2 = 3,

        /// <summary>A <c>ZQUANTIZ</c> this library does not know. Reported when the
        /// pixels are asked for, since dequantizing by the wrong rule would produce
        /// plausible but wrong values.</summary>
        Unknown = -1,
    }

    /// <summary>
    /// The dithered-quantization half of the tile compression convention: turning the
    /// integers a codec produced back into the floating-point values they stand for.
    /// <para>
    /// The random sequence is not a general-purpose one; it is a specific 10000-entry
    /// table that every implementation has to reproduce exactly, or the dither cannot
    /// be subtracted back off. It is generated by the Park and Miller minimal-standard
    /// generator seeded at 1, per the FITS tiled-image convention.
    /// </para>
    /// </summary>
    internal static class Quantizer
    {
        /// <summary>Length of the shared random-number table. Fixed by the convention.</summary>
        internal const int RandomCount = 10000;

        /// <summary>Quantized value standing for an undefined pixel.</summary>
        internal const int NullValue = -2147483647;

        /// <summary>Quantized value standing for a pixel that was exactly zero, under
        /// <see cref="QuantizationMethod.SubtractiveDither2"/>.</summary>
        internal const int ZeroValue = -2147483646;

        private static readonly double[] RandomValues = BuildRandomValues();

        private static double[] BuildRandomValues()
        {
            const double a = 16807.0;
            const double m = 2147483647.0;

            var values = new double[RandomCount];
            double seed = 1.0;
            for (int i = 0; i < RandomCount; i++)
            {
                double temp = a * seed;
                seed = temp - m * (int)(temp / m);
                values[i] = seed / m;
            }
            return values;
        }

        /// <summary>Convert one tile of quantized integers back to floating point.</summary>
        /// <param name="tileIndex">Zero-based index of the tile within the image. Together
        /// with <paramref name="ditherSeed"/> this picks the tile's place in the shared
        /// random sequence, so tiles can be decoded in any order and independently.</param>
        /// <param name="src">The quantized integers.</param>
        /// <param name="count">Number of pixels in the tile.</param>
        /// <param name="scale">The tile's <c>ZSCALE</c>.</param>
        /// <param name="zero">The tile's <c>ZZERO</c>.</param>
        /// <param name="method">The quantization method from <c>ZQUANTIZ</c>.</param>
        /// <param name="ditherSeed">The image's <c>ZDITHER0</c>.</param>
        /// <param name="hasBlank">Whether <c>ZBLANK</c> marks undefined pixels.</param>
        /// <param name="blank">The <c>ZBLANK</c> value, when <paramref name="hasBlank"/>.</param>
        /// <param name="dst">Destination, receiving <paramref name="count"/> values.
        /// Undefined pixels are written as NaN.</param>
        internal static void Unquantize(int tileIndex, int[] src, int count,
                                        double scale, double zero,
                                        QuantizationMethod method, int ditherSeed,
                                        bool hasBlank, int blank, double[] dst)
        {
            bool dithered = method == QuantizationMethod.SubtractiveDither1
                            || method == QuantizationMethod.SubtractiveDither2;
            bool preserveZeros = method == QuantizationMethod.SubtractiveDither2;

            if (!dithered)
            {
                for (int i = 0; i < count; i++)
                {
                    int v = src[i];
                    dst[i] = hasBlank && v == blank ? double.NaN : v * scale + zero;
                }
                return;
            }

            // The tile's starting point in the random sequence. Tile numbers are
            // 1-based in the convention, hence the -1 alongside the 0-based index here.
            int seedIndex = (tileIndex + ditherSeed - 1) % RandomCount;
            if (seedIndex < 0)
            {
                seedIndex += RandomCount;
            }
            int next = (int)(RandomValues[seedIndex] * 500);

            for (int i = 0; i < count; i++)
            {
                int v = src[i];
                if (hasBlank && v == blank)
                {
                    dst[i] = double.NaN;
                }
                else if (preserveZeros && v == ZeroValue)
                {
                    dst[i] = 0.0;
                }
                else
                {
                    dst[i] = (v - RandomValues[next] + 0.5) * scale + zero;
                }

                // Walking off the end of the table restarts at a fresh offset rather
                // than wrapping to zero, so a long tile does not simply repeat.
                next++;
                if (next == RandomCount)
                {
                    seedIndex++;
                    if (seedIndex == RandomCount)
                    {
                        seedIndex = 0;
                    }
                    next = (int)(RandomValues[seedIndex] * 500);
                }
            }
        }
    }
}
